[package]
name = "learn-treesitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.83"
ropey = "1.6.1"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"
